apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: etcd-pvc
  namespace: dev
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 8Gi
  storageClassName: nfs