apiVersion: v1
kind: PersistentVolume
metadata: 
  name: etcd-data-pv
  namespace: dev
spec: 
  capacity: 
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  storageClassName: nfs
  nfs: 
    server: 192.168.0.62
    path: /nfs/data/etcd-data