apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer-role
  namespace: dev  # 限定命名空间
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources:
    - pods
    - deployments
    - services
    - configmaps
    - secrets
    - jobs
    - cronjobs
    - ingresses
  verbs: ["get", "list", "create", "update", "patch", "delete"]
