apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: order-service
  name: order-service
  namespace: dev
spec: 
  replicas: 2
  revisionHistoryLimit: 10
  selector: 
    matchLabels: 
      app: order-service
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template: 
    metadata: 
      labels: 
        app: order-service
    spec: 
      restartPolicy: Always
      affinity: 
        podAntiAffinity: 
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm: 
              labelSelector: 
                matchExpressions: 
                - key: app 
                  operator: In
                  values: 
                  - "order-service"
              topologyKey: kubernetes.io/hostname
      containers: 
        - name: order-container
          image: 192.168.0.62/microservice/order:dev-b06fd015
          imagePullPolicy: IfNotPresent
          ports: 
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9000
          livenessProbe: 
            httpGet: 
              path: "/healthz"
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe: 
            httpGet: 
              path: "/ready"
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          resources: 
            requests: 
              cpu: "500m"
              memory: "256Mi"
            limits: 
              cpu: "1000m"
              memory: "512Mi"
      imagePullSecrets: 
        - name: myregcred