apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: product-service
  name: product-service
  namespace: dev
spec: 
  replicas: 2
  revisionHistoryLimit: 10
  selector: 
    matchLabels: 
      app: product-service
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template: 
    metadata: 
      labels: 
        app: product-service
    spec: 
      restartPolicy: Always
      affinity: 
        podAntiAffinity: 
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm: 
              labelSelector: 
                matchExpressions: 
                - key: app 
                  operator: In
                  values: 
                  - "product-service"
              topologyKey: kubernetes.io/hostname
        nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms: 
            - matchExpressions: 
              - key: node-role.kubernetes.io/infrastructure
                operator: NotIn
                values: 
                - "k8s-node3"
      containers: 
        - name: product-container
          image: 192.168.0.62/microservice/product:dev-b368fae5
          imagePullPolicy: IfNotPresent
          ports: 
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9000
          livenessProbe: 
            httpGet: 
              path: "/healthz"
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe: 
            httpGet: 
              path: "/ready"
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          resources: 
            requests: 
              cpu: "500m"
              memory: "256Mi"
            limits: 
              cpu: "1000m"
              memory: "512Mi"
      imagePullSecrets: 
        - name: myregcred